// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWY5aD6aQ3__bqtujzSme87sgB04RyiLg',
    appId: '1:458254541238:web:358b2ae5e1cea8e4766117',
    messagingSenderId: '458254541238',
    projectId: 'authentication-1597f',
    authDomain: 'authentication-1597f.firebaseapp.com',
    storageBucket: 'authentication-1597f.appspot.com',
    measurementId: 'G-8GC7303EFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMUkX2Ke9jYzJlF5Qr6BJmMb5D_G8Yahg',
    appId: '1:458254541238:android:55811ddc01605de9766117',
    messagingSenderId: '458254541238',
    projectId: 'authentication-1597f',
    storageBucket: 'authentication-1597f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGbH8w6wKKxsesRjyDEu4l3rQBTaUutqU',
    appId: '1:458254541238:ios:088511d3b4313833766117',
    messagingSenderId: '458254541238',
    projectId: 'authentication-1597f',
    storageBucket: 'authentication-1597f.appspot.com',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGbH8w6wKKxsesRjyDEu4l3rQBTaUutqU',
    appId: '1:458254541238:ios:a89000689fb5612b766117',
    messagingSenderId: '458254541238',
    projectId: 'authentication-1597f',
    storageBucket: 'authentication-1597f.appspot.com',
    iosBundleId: 'com.example.authentication.RunnerTests',
  );
}
